// Auto-generated by `cargo run -p c2pa-spec-codegen`.
// Do not edit by hand.

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ActionsMap {
    /// list of actions
    pub actions: Vec<ActionItemsMap>,
    /// additional information about the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum ActionChoice {
    #[serde(rename = "c2pa.addedText")]
    C2paAddedText,
    #[serde(rename = "c2pa.adjustedColor")]
    C2paAdjustedColor,
    #[serde(rename = "c2pa.changedSpeed")]
    C2paChangedSpeed,
    #[serde(rename = "c2pa.color_adjustments")]
    C2paColorAdjustments,
    #[serde(rename = "c2pa.converted")]
    C2paConverted,
    #[serde(rename = "c2pa.copied")]
    C2paCopied,
    #[serde(rename = "c2pa.created")]
    C2paCreated,
    #[serde(rename = "c2pa.cropped")]
    C2paCropped,
    #[serde(rename = "c2pa.deleted")]
    C2paDeleted,
    #[serde(rename = "c2pa.drawing")]
    C2paDrawing,
    #[serde(rename = "c2pa.dubbed")]
    C2paDubbed,
    #[serde(rename = "c2pa.edited")]
    C2paEdited,
    #[serde(rename = "c2pa.edited.metadata")]
    C2paEditedMetadata,
    #[serde(rename = "c2pa.filtered")]
    C2paFiltered,
    #[serde(rename = "c2pa.formatted")]
    C2paFormatted,
    #[serde(rename = "c2pa.managed")]
    C2paManaged,
    #[serde(rename = "c2pa.opened")]
    C2paOpened,
    #[serde(rename = "c2pa.orientation")]
    C2paOrientation,
    #[serde(rename = "c2pa.produced")]
    C2paProduced,
    #[serde(rename = "c2pa.placed")]
    C2paPlaced,
    #[serde(rename = "c2pa.printed")]
    C2paPrinted,
    #[serde(rename = "c2pa.published")]
    C2paPublished,
    #[serde(rename = "c2pa.redacted")]
    C2paRedacted,
    #[serde(rename = "c2pa.removed")]
    C2paRemoved,
    #[serde(rename = "c2pa.repackaged")]
    C2paRepackaged,
    #[serde(rename = "c2pa.resized")]
    C2paResized,
    #[serde(rename = "c2pa.resized.proportional")]
    C2paResizedProportional,
    #[serde(rename = "c2pa.saved")]
    C2paSaved,
    #[serde(rename = "c2pa.transcoded")]
    C2paTranscoded,
    #[serde(rename = "c2pa.translated")]
    C2paTranslated,
    #[serde(rename = "c2pa.trimmed")]
    C2paTrimmed,
    #[serde(rename = "c2pa.unknown")]
    C2paUnknown,
    #[serde(rename = "c2pa.version_updated")]
    C2paVersionUpdated,
    #[serde(rename = "c2pa.watermarked")]
    C2paWatermarked,
    #[serde(rename = "c2pa.watermarked.bound")]
    C2paWatermarkedBound,
    #[serde(rename = "c2pa.watermarked.unbound")]
    C2paWatermarkedUnbound,
    #[serde(rename = "font.edited")]
    FontEdited,
    #[serde(rename = "font.subset")]
    FontSubset,
    #[serde(rename = "font.createdFromVariableFont")]
    FontCreatedFromVariableFont,
    #[serde(rename = "font.charactersAdded")]
    FontCharactersAdded,
    #[serde(rename = "font.charactersDeleted")]
    FontCharactersDeleted,
    #[serde(rename = "font.charactersModified")]
    FontCharactersModified,
    #[serde(rename = "font.hinted")]
    FontHinted,
    #[serde(rename = "font.openTypeFeatureAdded")]
    FontOpenTypeFeatureAdded,
    #[serde(rename = "font.openTypeFeatureModified")]
    FontOpenTypeFeatureModified,
    #[serde(rename = "font.openTypeFeatureRemoved")]
    FontOpenTypeFeatureRemoved,
    #[serde(rename = "font.merged")]
    FontMerged,
    String(String),
}

pub type Buuid = serde_bytes::ByteBuf;

/// NOTE: an earlier version of this specification also included an "actors" field, however this was removed in version 2.0.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ActionItemsMap {
    pub action: ActionChoice,
    /// time-stamp of when the action occurred.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub when: Option<String>,
    /// The software agent that performed the action.
    #[serde(rename = "softwareAgent")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub software_agent: Option<String>,
    /// A semicolon-delimited list of the parts of the resource that were changed since the previous event history. If not present, presumed to be undefined. When tracking changes and the scope of the changed components is unknown, it can be assumed that anything could have changed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub changed: Option<String>,
    /// The value of the xmpMM:InstanceID property for the modified (output) resource
    #[serde(rename = "instanceID")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance_id: Option<Buuid>,
    /// Additional parameters of the action. These will often vary by the type of action
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<ParametersMap>,
    /// One of the defined source types at https://cv.iptc.org/newscodes/digitalsourcetype/
    #[serde(rename = "digitalSourceType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub digital_source_type: Option<String>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ParametersMap {
    /// A hashed-uri to the ingredient assertion that this action acts on
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ingredient: Option<HashedUriMap>,
    /// Additional description of the action
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub entries: std::collections::HashMap<String, ciborium::Value>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum ActionReason {
    #[serde(rename = "c2pa.PII.present")]
    C2paPiiPresent,
    #[serde(rename = "c2pa.invalid.data")]
    C2paInvalidData,
    #[serde(rename = "c2pa.tradesecret.present")]
    C2paTradesecretPresent,
    #[serde(rename = "c2pa.government.confidential")]
    C2paGovernmentConfidential,
    String(String),
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ActionsMapV2 {
    /// list of actions
    pub actions: Vec<ActionItemMapV2>,
    /// list of templates for the actions
    #[serde(skip_serializing_if = "Option::is_none")]
    pub templates: Option<Vec<ActionTemplateMapV2>>,
    /// A list of of the software/hardware that did the action
    #[serde(rename = "softwareAgents")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub software_agents: Option<Vec<GeneratorInfoMap>>,
    /// additional information about the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
    /// If true, indicates that all actions performed are included in an actions assertion
    #[serde(rename = "allActionsIncluded")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub all_actions_included: Option<bool>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ActionCommonMapV2 {
    /// Description of the software/hardware that did the action
    #[serde(rename = "softwareAgent")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub software_agent: Option<GeneratorInfoMap>,
    /// 0-based index into the softwareAgents array in the actions-map-2
    #[serde(rename = "softwareAgentIndex")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub software_agent_index: Option<i64>,
    /// Additional description of the action, important for custom actions
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// One of the defined source types at https://cv.iptc.org/newscodes/digitalsourcetype/ or in this specification
    #[serde(rename = "digitalSourceType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub digital_source_type: Option<String>,
}

/// NOTE: an earlier version of this specification also included an "actors" field, however this was removed in version 2.0.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ActionItemMapV2 {
    /// the type of action
    pub action: ActionChoice,
    /// now additional common items
    #[serde(rename = "action-common-map-v2")]
    pub action_common_map_v2: ActionCommonMapV2,
    /// time-stamp of when the action occurred.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub when: Option<String>,
    /// A list of the regions of interest of the resource that were changed. If not present, presumed to be undefined.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub changes: Option<Vec<RegionMap>>,
    /// List of related actions
    #[serde(skip_serializing_if = "Option::is_none")]
    pub related: Option<Vec<ActionItemMapV2>>,
    /// the reason why this action was performed, required when the action is `c2pa.redacted`
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<ActionReason>,
    /// Additional parameters of the action. These will often vary by the type of action
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<ParametersMapV2>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ActionTemplateMapV2 {
    /// templates support the additional special "*" option
    pub action: ciborium::Value,
    /// additional common items
    #[serde(rename = "action-common-map-v2")]
    pub action_common_map_v2: ActionCommonMapV2,
    /// hashed_uri reference to an embedded data assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<HashedUriMap>,
    /// Additional parameters of the template.
    #[serde(rename = "templateParameters")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub template_parameters: Option<ParametersCommonMapV2>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ParametersCommonMapV2 {
    pub entries: std::collections::HashMap<String, ciborium::Value>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ParametersMapV2 {
    /// A JUMBF URI to the redacted assertion, required when the action is `c2pa.redacted`
    #[serde(skip_serializing_if = "Option::is_none")]
    pub redacted: Option<crate::jumbf_uri::JumbfUri>,
    /// A list of hashed JUMBF URI(s) to the ingredient (v2 or v3) assertion(s) that this action acts on
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ingredients: Option<Vec<HashedUriMap>>,
    /// BCP-47 code of the source language of a `c2pa.translated` action
    #[serde(rename = "sourceLanguage")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_language: Option<String>,
    /// BCP-47 code of the target language of a `c2pa.translated` action
    #[serde(rename = "targetLanguage")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target_language: Option<String>,
    /// was this action performed multiple times
    #[serde(rename = "multipleInstances")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub multiple_instances: Option<bool>,
    /// anything from the common parameters
    #[serde(rename = "parameters-common-map-v2")]
    pub parameters_common_map_v2: ParametersCommonMapV2,
}

/// Describes a reference to an alternative version of the content
/// (e.g. an original preservation image in Exif, a secure capture from TEE, etc.)
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum AlternativeContentRepresentation {
    OriginalPreservationImageRepresentation(OriginalPreservationImageRepresentation),
    GenericRepresentation(GenericRepresentation),
}

/// The original-preservation-image-representation describes the location of the original captured scene image.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct OriginalPreservationImageRepresentation {
    #[serde(rename = "type")]
    pub type_: String,
    pub parameters: OriginalPreservationImageParams,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct OriginalPreservationImageParams {
    /// The zero-based index of the element within the parts array of the corresponding c2pa.hash.multi-asset assertion that uniquely identifies the location of the OPI.
    #[serde(rename = "multiAssetPartIndex")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub multi_asset_part_index: Option<u64>,
    /// hashed URI reference to the embedded data assertion containing OPI, or to another assertion that is technically equivalent to an embedded data assertion (e.g., c2pa.thumbnail.claim).
    #[serde(rename = "embeddedOriginalPreservationImage")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub embedded_original_preservation_image: Option<HashedUriMap>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct GenericRepresentation {
    #[serde(rename = "type")]
    pub type_: String,
    pub entries: std::collections::HashMap<String, std::collections::HashMap<String, ciborium::Value>>,
}

/// Describes additional information about an assertion, including a hashed-uri reference to it. We use a socket/plug here to allow hashed-uri-map to be used in individual files without having the map defined in the same file
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct AssertionMetadataMap {
    /// The RFC 3339 date-time string when the assertion was created/generated
    #[serde(rename = "dateTime")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub date_time: Option<String>,
    /// Ratings given to the assertion (may be empty)
    #[serde(rename = "reviewRatings")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub review_ratings: Option<Vec<RatingMap>>,
    /// hashed_uri reference to another assertion that this review is about
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reference: Option<HashedUriMap>,
    /// A description of the source of the assertion data, selected from a predefined list
    #[serde(rename = "dataSource")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_source: Option<SourceMap>,
    /// localizations for strings in the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub localizations: Option<Vec<LocalizationDataEntry>>,
    /// describes a region of the asset where this assertion is relevant
    #[serde(rename = "regionOfInterest")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region_of_interest: Option<RegionMap>,
}

/// the following two values of source-type are deprecated as of 2.0
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum SourceType {
    #[serde(rename = "signer")]
    Signer,
    #[serde(rename = "claimGenerator.REE")]
    ClaimGeneratorRee,
    #[serde(rename = "claimGenerator.TEE")]
    ClaimGeneratorTee,
    #[serde(rename = "localProvider.REE")]
    LocalProviderRee,
    #[serde(rename = "localProvider.TEE")]
    LocalProviderTee,
    #[serde(rename = "remoteProvider.1stParty")]
    RemoteProvider1stParty,
    #[serde(rename = "remoteProvider.3rdParty")]
    RemoteProvider3rdParty,
    #[serde(rename = "humanEntry")]
    HumanEntry,
    /// the following two values of source-type are deprecated as of 2.0
    #[serde(rename = "humanEntry.anonymous")]
    HumanEntryAnonymous,
    #[serde(rename = "humanEntry.identified")]
    HumanEntryIdentified,
}

/// NOTE: an earlier version of this specification also included an "actors" field, however this was removed in version 2.0.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct SourceMap {
    /// A value from among the enumerated list indicating whether the source of the assertion is a claim generator running in a rich execution environment (REE), a claim generator running in a trusted execution environment (TEE), a local data provider in REE (e.g. the location API from a mobile operating system), a local data running in a TEE (e.g. a trusted location trusted app from a chipset vendor), a remote data provider such as a server (e.g. Google's geolocation API service), or entry by a human.
    #[serde(rename = "type")]
    pub type_: SourceType,
    /// A human readable string giving details about the source of the assertion data, e.g. the URL of the remote server that provided the data
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
}

pub type IntRange = u64;

/// the following three values of review-code are deprecated as of 2.0
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum ReviewCode {
    #[serde(rename = "actions.unknownActionsPerformed")]
    ActionsUnknownActionsPerformed,
    #[serde(rename = "actions.missing")]
    ActionsMissing,
    #[serde(rename = "actions.possiblyMissing")]
    ActionsPossiblyMissing,
    #[serde(rename = "depthMap.sceneMismatch")]
    DepthMapSceneMismatch,
    #[serde(rename = "ingredient.modified")]
    IngredientModified,
    #[serde(rename = "ingredient.possiblyModified")]
    IngredientPossiblyModified,
    #[serde(rename = "thumbnail.primaryMismatch")]
    ThumbnailPrimaryMismatch,
    /// the following three values of review-code are deprecated as of 2.0
    #[serde(rename = "stds.iptc.location.inaccurate")]
    StdsIptcLocationInaccurate,
    #[serde(rename = "stds.schema-org.CreativeWork.misattributed")]
    StdsSchemaOrgCreativeWorkMisattributed,
    #[serde(rename = "stds.schema-org.CreativeWork.missingAttribution")]
    StdsSchemaOrgCreativeWorkMissingAttribution,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct RatingMap {
    /// "A value from 1 (worst) to 5 (best) of the rating of the item"
    pub value: IntRange,
    /// A label-formatted string that describes the reason for the rating
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<ReviewCode>,
    /// A human readable string explaining why the rating is what it is
    #[serde(skip_serializing_if = "Option::is_none")]
    pub explanation: Option<String>,
}

/// The data structures used to store localization dictionaries
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct LocalizationDataEntry {
    #[serde(rename = "language-string")]
    pub language_string: LanguageString,
}

pub type LanguageString = String;

/// Assertion that describes additional information about an assertion, including a hashed-uri reference to it
pub type AssertionMetadataAssertion = AssertionMetadataMap;

/// The asset reference assertion (ARA) describes where a copy of the asset may be obtained.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct AssetRefMap {
    pub references: Vec<AraReferenceBlockMap>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct AraReferenceBlockMap {
    pub reference: AraReferenceUriMap,
    /// Human readable description of the location.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct AraReferenceUriMap {
    /// URI reference a location where a copy of the asset may be obtained from
    pub uri: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum TypeChoice {
    #[serde(rename = "c2pa.types.classifier")]
    C2paTypesClassifier,
    #[serde(rename = "c2pa.types.cluster")]
    C2paTypesCluster,
    #[serde(rename = "c2pa.types.dataset")]
    C2paTypesDataset,
    #[serde(rename = "c2pa.types.dataset.jax")]
    C2paTypesDatasetJax,
    #[serde(rename = "c2pa.types.dataset.keras")]
    C2paTypesDatasetKeras,
    #[serde(rename = "c2pa.types.dataset.ml_net")]
    C2paTypesDatasetMlNet,
    #[serde(rename = "c2pa.types.dataset.mxnet")]
    C2paTypesDatasetMxnet,
    #[serde(rename = "c2pa.types.dataset.onnx")]
    C2paTypesDatasetOnnx,
    #[serde(rename = "c2pa.types.dataset.openvino")]
    C2paTypesDatasetOpenvino,
    #[serde(rename = "c2pa.types.dataset.pytorch")]
    C2paTypesDatasetPytorch,
    #[serde(rename = "c2pa.types.dataset.tensorflow")]
    C2paTypesDatasetTensorflow,
    #[serde(rename = "c2pa.types.format.numpy")]
    C2paTypesFormatNumpy,
    #[serde(rename = "c2pa.types.format.protobuf")]
    C2paTypesFormatProtobuf,
    #[serde(rename = "c2pa.types.format.pickle")]
    C2paTypesFormatPickle,
    #[serde(rename = "c2pa.types.generator")]
    C2paTypesGenerator,
    #[serde(rename = "c2pa.types.generator.prompt")]
    C2paTypesGeneratorPrompt,
    #[serde(rename = "c2pa.types.generator.seed")]
    C2paTypesGeneratorSeed,
    #[serde(rename = "c2pa.types.model")]
    C2paTypesModel,
    #[serde(rename = "c2pa.types.model.jax")]
    C2paTypesModelJax,
    #[serde(rename = "c2pa.types.model.keras")]
    C2paTypesModelKeras,
    #[serde(rename = "c2pa.types.model.ml_net")]
    C2paTypesModelMlNet,
    #[serde(rename = "c2pa.types.model.mxnet")]
    C2paTypesModelMxnet,
    #[serde(rename = "c2pa.types.model.onnx")]
    C2paTypesModelOnnx,
    #[serde(rename = "c2pa.types.model.openvino")]
    C2paTypesModelOpenvino,
    #[serde(rename = "c2pa.types.model.openvino.parameter")]
    C2paTypesModelOpenvinoParameter,
    #[serde(rename = "c2pa.types.model.openvino.topology")]
    C2paTypesModelOpenvinoTopology,
    #[serde(rename = "c2pa.types.model.pytorch")]
    C2paTypesModelPytorch,
    #[serde(rename = "c2pa.types.model.tensorflow")]
    C2paTypesModelTensorflow,
    #[serde(rename = "c2pa.types.regressor")]
    C2paTypesRegressor,
    #[serde(rename = "c2pa.types.tensorflow.hubmodule")]
    C2paTypesTensorflowHubmodule,
    #[serde(rename = "c2pa.types.tensorflow.savedmodel")]
    C2paTypesTensorflowSavedmodel,
    String(String),
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct AssetTypeMap {
    /// one of the listed choices or a custom value
    #[serde(rename = "type")]
    pub type_: TypeChoice,
    /// The version of the asset type, if applicable. This is a SemVer formatted string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<SemverString>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct AssetTypes {
    /// IANA media type of the asset
    #[serde(rename = "dc:format")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dc_format: Option<FormatString>,
    /// a collection of types related to the asset
    #[serde(skip_serializing_if = "Option::is_none")]
    pub types: Option<Vec<AssetTypeMap>>,
    /// additional information about the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct BmffHashMap {
    pub exclusions: Vec<ExclusionsMap>,
    /// A string identifying the cryptographic hash algorithm used to compute this hash, taken from the C2PA hash algorithm identifier list. If this field is absent, the hash algorithm is taken from an enclosing structure as defined by that structure. If both are present, the field in this structure is used. If no value is present in any of these places, this structure is invalid; there is no default.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alg: Option<String>,
    /// For non-fragmented MP4, this is the hash of the entire BMFF file excluding boxes listed in the exclusions array.  For fragmented MP4 (live or VOD), this field is the hash of the segment excluding boxes listed in the exclusions array.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hash: Option<serde_bytes::ByteBuf>,
    /// A set of Merkle tree rows and the associated data required to enable verification of a single 'mdat' box, multiple 'mdat' boxes, and/or individual fragment files within the asset.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub merkle: Option<Vec<MerkleMap>>,
    /// optional) a human-readable description of what this hash covers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Unused and deprecated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// in a live video workflow, the monotonically increasing sequence number for each segment
    #[serde(rename = "sequenceNumber")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence_number: Option<u64>,
}

/// (optional) CBOR byte string of exactly 3 bytes.
pub type FlagType = serde_bytes::ByteBuf;

pub type FlagT = FlagType;

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ExclusionsMap {
    /// Location of box(es) to exclude from the hash starting from the root node as an xpath formatted string of version https://www.w3.org/TR/xpath-10/ with highly constrained syntax.
    pub xpath: String,
    /// (optional) Length that a leafmost box must have to exclude from the hash.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub length: Option<u64>,
    /// (optional) The data in the leafmost box at the specified relative byte offset must be identical to the specified data for the box to be excluded from the hash.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<DataMap>>,
    /// (optional) Only this portion of the excluded box is excluded from the hash.  Each entry in the array must have a monotonically increasing relative byte offset.  No subset within the array may overlap.  The last entry may have a length of zero; this indicates that the remainder of the box from that relative byte offset onward is excluded.  A relative byte offset or relative byte offset plus length that exceeds the length of the box is allowed; bytes beyond the end of the box are never hashed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subset: Option<Vec<SubsetMap>>,
    /// (optional) Version that must be set in a leafmost box for the box to be excluded from the hash.  Only specified for a box that inherits from FullBox.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<i64>,
    /// (optional) byte string of exactly 3 bytes.  The 24-bit flags that must be set in a leafmost box for the box to be excluded from the hash.  Only specified for a box that inherits from FullBox.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flags: Option<FlagT>,
    /// (optional) indicates that flags must be an exact match.  If not specified, defaults to true.  Only specified for a box that inherits from FullBox and when flags is also specified.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exact: Option<bool>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct DataMap {
    pub offset: u64,
    pub value: serde_bytes::ByteBuf,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct SubsetMap {
    pub offset: u64,
    pub length: u64,
}

/// Each entry in a map is a Merkle tree row and the associated data required to enable validation of a single
/// 'mdat' box or multiple 'mdat' boxes within the asset.",
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct MerkleMap {
    /// 1-based unique id used to differentiate across files to determine which Merkle tree should be used to validate a given 'mdat' box.
    #[serde(rename = "uniqueId")]
    pub unique_id: i64,
    /// A local id indicating Merkle tree.
    #[serde(rename = "localId")]
    pub local_id: i64,
    /// Number of leaf nodes in the Merkle tree.  Null nodes are not included in this count.
    pub count: i64,
    /// A string identifying the cryptographic hash algorithm used to compute the hashes in this Merkle tree, taken from the C2PA hash algorithm identifier list. If this field is absent, the hash algorithm is taken from the `alg` value of the enclosing structure as defined by that structure. If both are present, the field in this structure is used. If no value is present in any of these places, this structure is invalid; there is no default.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alg: Option<String>,
    /// For fragmented MP4 assets that are split across multiple files, this field is required to be present and is the hash of the entire initialization segment file for chunks hashed by this Merkle tree excluding boxes listed in the exclusions array.  For fragmented MP4 assets that are stored as a single flat MP4 file, this field is required to be present and is the hash of all bytes preceding the first 'moof' box excluding boxes listed in the exclusions array.  For non-fragmented MP4, this field is required to be absent.
    #[serde(rename = "initHash")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub init_hash: Option<serde_bytes::ByteBuf>,
    /// An ordered array representing a single row of the Merkle tree, which may be the leaf-most row, root row, or any intermediate row. Any null nodes are excluded. The depth of the row is implied by (is computed from) the number of items in this array.
    pub hashes: Vec<serde_bytes::ByteBuf>,
    /// For non-fragmented MP4 assets where the mdat box is validated piecewise, this field can be present. This field is the non-negative size in bytes of a given leaf node in the Merkle tree. For fragmented MP4, this field is not present.
    #[serde(rename = "fixedBlockSize")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fixed_block_size: Option<u64>,
    /// For non-fragmented MP4 assets where the mdat box is validated piecewise, this field can be present. Each entry in the array corresponds to the non-negative size in bytes of a given leaf node in the Merkle tree. The number of elements is equal to `count` and sum of the values is equal to size of payload of mdat. For fragmented MP4, this field is not present.
    #[serde(rename = "variableBlockSizes")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub variable_block_sizes: Option<Vec<i64>>,
}

/// The data structure used to store sufficient information to validate a single 'mdat' box or
/// a portion of an 'mdat' box when a Merkle tree is used",
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct BmffMerkleMap {
    /// A unique integer used to differentiate local ids
    #[serde(rename = "uniqueId")]
    pub unique_id: i64,
    /// A local id indicating Merkle tree.
    #[serde(rename = "localId")]
    pub local_id: i64,
    /// Zero-based index into the leaf-most Merkle tree row corresponding to this 'mdat' box or portion of this 'mdat' box
    pub location: i64,
    /// An ordered array representing the set of additional hashes required to reach a hash in the Merkle tree specified in the manifest from leaf-most (peer of this node) to root-most (child of node in manifest).  Note that this array may not be present, e.g. if the manifest itself contains the leaf-most row of the Merkle tree.  Null hashes are not included in this array.  The algorithm used is determined using the `alg` field from the corresponding entry in the `merkle` field array in the BMFF hash structure.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hashes: Option<Vec<serde_bytes::ByteBuf>>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct BoxMap {
    pub boxes: Vec<BoxHashMap>,
    /// A string identifying the cryptographic hash algorithm used to compute the hash in this assertion, taken from the C2PA hash algorithm identifier list. If this field is absent, the hash algorithm is taken the `alg` value of the enclosing structure. If both are present, the field in this structure is used. If no value is present in any of these places, this structure is invalid; there is no default.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alg: Option<String>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct BoxHashMap {
    /// An array of strings representing the box identifiers in order of appearance (e.g., `APP0`, `IHDR`)
    pub names: Vec<BoxName>,
    /// A string identifying the cryptographic hash algorithm used to compute the hash in this assertion, taken from the C2PA hash algorithm identifier list. If this field is absent, the hash algorithm is taken the `alg` value of the enclosing structure. If both are present, the field in this structure is used. If no value is present in any of these places, this structure is invalid; there is no default.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alg: Option<String>,
    /// byte string of the hash value
    pub hash: serde_bytes::ByteBuf,
    /// A boolean value indicating whether a validator can ignore this box ( & associated hash) during validation. If this field is absent, the box is hashed and the values compared.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub excluded: Option<bool>,
    /// An array of hash exclusion ranges. Ranges have monotonically increasing `start` values, and no two ranges may overlap.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclusions: Option<Vec<BoxExclusionsMap>>,
    /// zero-filled byte string used for filling up space
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pad: Option<serde_bytes::ByteBuf>,
    /// zero-filled byte string used for filling up space
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pad2: Option<serde_bytes::ByteBuf>,
}

pub type BoxName = String;

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct BoxExclusionsMap {
    /// Starting byte offset (from the start of the box) of the range
    pub start: u64,
    /// Number of bytes of data to exclude
    pub length: u64,
    /// 0-based index into the names array in the box-hash-map. Can be omitted if the number of box is one.
    #[serde(rename = "boxIndex")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub box_index: Option<i64>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct CertificateStatusMap {
    #[serde(rename = "ocspVals")]
    pub ocsp_vals: Vec<serde_bytes::ByteBuf>,
}

/// CDDL schema for a claim map in C2PA
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ClaimMap {
    /// A User-Agent string formatted as per http://tools.ietf.org/html/rfc7231#section-5.5.3, for including the name and version of the claims generator that created the claim
    pub claim_generator: String,
    pub claim_generator_info: Vec<GeneratorInfoMap>,
    /// JUMBF URI reference to the signature of this claim
    pub signature: crate::jumbf_uri::JumbfUri,
    pub assertions: Vec<HashedUriMap>,
    /// media type of the asset
    #[serde(rename = "dc:format")]
    pub dc_format: String,
    /// uniquely identifies a specific version of an asset
    #[serde(rename = "instanceID")]
    pub instance_id: String,
    /// name of the asset,
    #[serde(rename = "dc:title")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dc_title: Option<String>,
    /// List of JUMBF URI references to the assertions of ingredient manifests being redacted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub redacted_assertions: Option<Vec<crate::jumbf_uri::JumbfUri>>,
    /// A string identifying the cryptographic hash algorithm used to compute all data hash assertions listed in this claim unless otherwise overridden, taken from the C2PA data hash algorithm identifier registry. This provides the value for the 'alg' field in data-hash and hashed-uri structures contained in this claim
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alg: Option<String>,
    /// A string identifying the algorithm used to compute all soft binding assertions listed in this claim unless otherwise overridden, taken from the C2PA soft binding algorithm identifier registry."
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alg_soft: Option<String>,
    /// additional information about the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
}

/// CDDL schema for a claim map in C2PA
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ClaimMapV2 {
    /// uniquely identifies a specific version of an asset
    #[serde(rename = "instanceID")]
    pub instance_id: String,
    /// the claim generator of this claim
    pub claim_generator_info: GeneratorInfoMap,
    /// JUMBF URI reference to the signature of this claim
    pub signature: crate::jumbf_uri::JumbfUri,
    pub created_assertions: Vec<HashedUriMap>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gathered_assertions: Option<Vec<HashedUriMap>>,
    /// name of the asset,
    #[serde(rename = "dc:title")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dc_title: Option<String>,
    /// List of JUMBF URI references to the assertions of ingredient manifests being redacted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub redacted_assertions: Option<Vec<crate::jumbf_uri::JumbfUri>>,
    /// A string identifying the cryptographic hash algorithm used to compute all data hash assertions listed in this claim unless otherwise overridden, taken from the C2PA data hash algorithm identifier registry. This provides the value for the 'alg' field in data-hash and hashed-uri structures contained in this claim
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alg: Option<String>,
    /// A string identifying the algorithm used to compute all soft binding assertions listed in this claim unless otherwise overridden, taken from the C2PA soft binding algorithm identifier registry."
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alg_soft: Option<String>,
    /// The version of the specification used to produce this claim (SemVer)
    #[serde(rename = "specVersion")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub spec_version: Option<SemverString>,
    /// (DEPRECATED) additional information about the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct GeneratorInfoMap {
    /// A human readable string naming the claim generator
    pub name: String,
    /// A human readable string of the product's version
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// hashed URI to the icon (either embedded or remote)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<ciborium::Value>,
    /// A human readable string of the operating system the claim generator is running on
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operating_system: Option<String>,
    pub entries: std::collections::HashMap<String, ciborium::Value>,
}

/// Assertion that references the actual assertion stored in the cloud
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct CloudDataMap {
    /// label for the cloud-based assertion (eg.c2pa.actions)
    pub label: String,
    /// Number of bytes of data
    pub size: SizeType,
    /// http(s) URL to where the cloud-hosted assertion can be found
    pub location: HashedExtUriMap,
    /// media/MIME type for the data
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    /// additional information about the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
}

/// size is minimum 1 in multiples of 1.0
pub type SizeType = i64;

/// An array of URIs and their associated hashes
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct CollectionDataHashMap {
    pub uris: Vec<UriHashedDataMap>,
    /// A string identifying the cryptographic hash algorithm used to compute the hash on each entry of the `uris` array, taken from the C2PA hash algorithm identifier list.
    pub alg: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub zip_central_directory_hash: Option<serde_bytes::ByteBuf>,
}

/// The data structure used to store a reference to a URI and its hash.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct UriHashedDataMap {
    /// relative URI reference
    pub uri: RelativeUrlType,
    ///  byte string containing the hash value
    pub hash: serde_bytes::ByteBuf,
    /// Number of bytes of data
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<SizeType>,
    /// IANA media type of the data
    #[serde(rename = "dc:format")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dc_format: Option<FormatString>,
    /// additional information about the data's type
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_types: Option<Vec<AssetTypeMap>>,
}

/// with CBOR Head (#) and tail ($) are introduced in regexp, so not needed explicitly
pub type RelativeUrlType = String;

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct DataBoxMap {
    /// IANA media type of the data
    #[serde(rename = "dc:format")]
    pub dc_format: FormatString,
    /// arbitrary text/binary data
    pub data: serde_bytes::ByteBuf,
    /// additional information about the data's type
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_types: Option<Vec<AssetTypeMap>>,
}

/// Also check optionality within the hash-map
/// The data structure used to store the cryptographic hash of some or all of the asset's data
/// and additional information required to compute the hash.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct DataHashMap {
    /// Ranges have monotonically increasing `start` values, and no two ranges may overlap.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclusions: Option<Vec<ExclusionRangeMap>>,
    /// A string identifying the cryptographic hash algorithm used to compute the hash in this assertion, taken from the C2PA hash algorithm identifier list. If this field is absent, the hash algorithm is taken the `alg` value of the enclosing structure. If both are present, the field in this structure is used. If no value is present in any of these places, this structure is invalid; there is no default.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alg: Option<String>,
    /// byte string of the hash value
    pub hash: serde_bytes::ByteBuf,
    /// zero-filled byte string used for filling up space
    pub pad: serde_bytes::ByteBuf,
    /// zero-filled byte string used for filling up space
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pad2: Option<serde_bytes::ByteBuf>,
    /// (optional) a human-readable description of what this hash cover
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Unused and deprecated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ExclusionRangeMap {
    /// Starting byte of the range
    pub start: u64,
    /// Number of bytes of data to exclude
    pub length: u64,
}

/// Assertion that encodes a GDepth-formatted 3D depth map of the captured scene
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct DepthmapGdepthMap {
    /// The format that describes how to convert the depthmap data into a valid float-point depthmap. Current valid values are 'RangeInverse' and 'RangeLinear'
    #[serde(rename = "GDepth:Format")]
    pub gdepth_format: FormatType,
    /// The near value of the depthmap in depth units
    #[serde(rename = "GDepth:Near")]
    pub gdepth_near: f64,
    /// The far value of the depthmap in depth units
    #[serde(rename = "GDepth:Far")]
    pub gdepth_far: f64,
    ///  The mime type for the base64 string describing the depth image content, e.g. 'image/jpeg' or 'image/png'",
    #[serde(rename = "GDepth:Mime")]
    pub gdepth_mime: MimeType,
    /// The base64 encoded depth image. See GDepth encoding page at developers.google.com. The depthmap will be stretched-to-fit the corresponding color image
    #[serde(rename = "GDepth:Data")]
    pub gdepth_data: Base64StringType,
    /// The units of the depthmap, e.g. 'm' for meters or 'mm' for millimeters
    #[serde(rename = "GDepth:Units")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gdepth_units: Option<UnitType>,
    /// The type of depth measurement. Current valid values are 'OpticalAxis' and 'OpticRay
    #[serde(rename = "GDepth:MeasureType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gdepth_measure_type: Option<DepthMeasType>,
    /// The mime type for the base64 string describing the confidence image content, e.g. 'image/png'.",
    #[serde(rename = "GDepth:ConfidenceMime")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gdepth_confidence_mime: Option<ConfidenceMimeType>,
    /// The base64 encoded confidence image. See GDepth encoding page at developers.google.com. The confidence map should have the same size as the depthmap
    #[serde(rename = "GDepth:Confidence")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gdepth_confidence: Option<Base64StringType>,
    /// The manufacturer of the device that created this depthmap
    #[serde(rename = "GDepth:Manufacturer")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gdepth_manufacturer: Option<String>,
    /// The model of the device that created this depthmap
    #[serde(rename = "GDepth:Model")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gdepth_model: Option<String>,
    /// The software that created this depthmap
    #[serde(rename = "GDepth:Software")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gdepth_software: Option<String>,
    /// The width in pixels of the original color image associated to this depthmap. This is NOT the depthmap width. If present, apps must update this property when scaling, cropping or rotating the color image. Clients use this property to verify the integrity of the depthmap w.r.t. the color image
    #[serde(rename = "GDepth:ImageWidth")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gdepth_image_width: Option<f64>,
    /// The height in pixels of the original color image associated to this depthmap. This is NOT the depthmap height. If present, apps must update this property when scaling, cropping or rotating the color image. Clients use this property to verify the integrity of the depthmap w.r.t. the color image
    #[serde(rename = "GDepth:ImageHeight")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gdepth_image_height: Option<f64>,
    /// additional information about the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
}

pub type Base64StringType = String;

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum MimeChoice {
    #[serde(rename = "image/jpeg")]
    ImageJpeg,
    #[serde(rename = "image/png")]
    ImagePng,
}

pub type MimeType = MimeChoice;

pub type ConfidenceMimeType = MimeChoice;

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum FormatChoice {
    RangeInverse,
    RangeLinear,
}

pub type FormatType = FormatChoice;

/// Unit can be meter represented as "m" or could be millimeter represented as "mm"
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum UnitChoice {
    /// Unit can be meter represented as "m" or could be millimeter represented as "mm"
    #[serde(rename = "m")]
    M,
    #[serde(rename = "mm")]
    Mm,
}

pub type UnitType = UnitChoice;

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum DepthMeasChoice {
    OpticalAxis,
    OpticRay,
}

pub type DepthMeasType = DepthMeasChoice;

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct EndorsementTargetMap {
    /// A DER-encoded SubjectPublicKeyInfo containing the public key
    #[serde(rename = "endorseeCredential")]
    pub endorsee_credential: PublicCredential,
    /// The date-time that this endorsement valid from, before this time it is not valid
    #[serde(rename = "notValidBefore")]
    pub not_valid_before: String,
    /// The date-time that this endorsement expires and is no longer valid
    #[serde(rename = "notValidAfter")]
    pub not_valid_after: String,
    /// additional information about the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct PublicCredential {
    /// an extensible field allowing the specification of the credential payload
    #[serde(rename = "credential-type")]
    pub credential_type: ciborium::Value,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum CredentialType {
    N1,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct EnvironmentalSustainabilityMap {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub energy_kwh: Option<EnvironmentalSustainabilityMeasurementMap>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub carbon_kgco2e: Option<EnvironmentalSustainabilityMeasurementMap>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub water_litres: Option<EnvironmentalSustainabilityMeasurementMap>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
    /// allow for any other custom use case
    pub entries: std::collections::HashMap<String, ciborium::Value>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct EnvironmentalSustainabilityMeasurementMap {
    pub value: f64,
    #[serde(rename = "measurementMethod")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub measurement_method: Option<SustainabilityMeasurementMethod>,
}

pub type SustainabilityMeasurementMethod = String;

/// Assertion that references assertion data stored externally by URI (no hash)
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ExternalReferenceMap {
    /// specifies the location and type of the remote data
    pub location: UnhashedExtUriMap,
}

/// Multiple font actions work with respect to ranges of Unicode values.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct FontUnicodeRangeMap {
    /// Inclusive start
    pub start: u64,
    /// Inclusive end
    pub stop: u64,
}

/// Font parameter used by font.subset, font.charactersAdded,
/// font.charactersDeleted, and font.charactersModified.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct FontParameterUnicodeRangesMap {
    /// Array of unicode ranges
    pub ranges: Vec<FontUnicodeRangeMap>,
}

/// Ranges for font instantiation parameters
pub type FontWeightRange = u64;

pub type FontWidthRange = f64;

pub type FontSlantRange = f64;

/// Font parameters used when creating an instance of a font from a variable font.
/// The different 'variation axis` for the fonts are detailed here.  The tag
/// names for the different axes are in parenthesis in the comments for each
/// parameter.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct FontParameterCreatedFromVariableFontMap {
    /// Weight(wght) or thickness of the font to be instantiated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub weight: Option<FontWeightRange>,
    /// Width(wdth) or narrowness of the letterforms of font to be instantiated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<FontWidthRange>,
    /// Get the italic(ital) version of the font.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub italic: Option<bool>,
    /// The slant(slnt) angle of the font.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub slant: Option<FontSlantRange>,
    /// The optical size(opsz) of the font, typically you want to match the font size requested.
    #[serde(rename = "optical-size")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub optical_size: Option<ciborium::Value>,
    /// Name and type of the custom axes.
    pub entries: std::collections::HashMap<String, ciborium::Value>,
}

/// Assertion data for font.info assertion.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct FontInfoMap {
    /// The full name of the font.
    #[serde(rename = "fullName")]
    pub full_name: String,
    /// A version in the semantic versioning (semver) format.
    /// The version of the font in SemVer format.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<SemverString>,
    /// A URL to the release notes associated with this version of the font.
    #[serde(rename = "versionUrl")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version_url: Option<ExtUrlType>,
    /// The date this version of the font was released or published.
    #[serde(rename = "releaseDate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub release_date: Option<String>,
    /// The Font Family.
    #[serde(rename = "familyName")]
    pub family_name: String,
    /// The style of the font, e.g. italic or regular.
    pub style: FontStyle,
    /// The weight of the font with name and value.
    pub weight: FontWeightMap,
    /// The PostScript name, ID 6, from the font 'name' table.
    /// Characters from ASCII 33-126 except the following: [](){}<>/%
    #[serde(rename = "postScriptName")]
    pub post_script_name: String,
    /// The format of this font.
    pub format: FontFormatChoice,
    /// The copyright associated with this font.
    #[serde(rename = "copyrightNotice")]
    pub copyright_notice: String,
    /// The entity that holds the copyright to the font.
    #[serde(rename = "copyrightHolder")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub copyright_holder: Option<FontEntityMap>,
    /// The years for which the holder asserts copyright.
    #[serde(rename = "copyrightYears")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub copyright_years: Option<Vec<FontCopyrightYearRange>>,
    /// The individuals that designed the font.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub designers: Option<Vec<FontDesignerMap>>,
    /// The foundry that designed the font.
    #[serde(rename = "designFoundry")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub design_foundry: Option<FontEntityMap>,
    /// The foundry that distributes the font.
    #[serde(rename = "sourceFoundry")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_foundry: Option<FontEntityMap>,
    /// Internal identier of font for foundry or vendor use.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
}

/// Font Formats
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum FontFormatChoice {
    /// Font Formats
    TrueType,
    OpenType,
}

/// Copyright year range
pub type FontCopyrightYearRange = u64;

/// Font weight class descriptors
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum FontWeightClass {
    /// Font weight class descriptors
    Microline,
    Hairline,
    UltraThin,
    ExtraThin,
    Thin,
    UltraLight,
    ExtraLight,
    Light,
    SemiLight,
    Book,
    Normal,
    Regular,
    Medium,
    DemiBold,
    SemiBold,
    Bold,
    Heavy,
    ExtraBold,
    UltraBold,
    SemiBlack,
    Black,
    ExtraBlack,
    UltraBlack,
    MegaBlack,
}

/// The font style
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum FontStyle {
    /// The font style
    Normal,
    Italic,
    Oblique,
    Roman,
    Regular,
}

/// Data for a font weight
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct FontWeightMap {
    /// The descriptive name of the weight class, e.g. bold or thin.
    pub class: FontWeightClass,
    /// The value of the weight.
    pub value: FontWeightRange,
}

/// Data for an entity with a name and credentials
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct FontEntityMap {
    /// The name of the person or foundry.
    pub name: String,
    /// A URL for additional information about this person or foundry.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<ExtUrlType>,
}

/// Data for a font designer
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct FontDesignerMap {
    /// The person who designed the font.
    pub person: FontEntityMap,
    /// The name of the foundry with which the designer was associated when contributing to the font design.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub foundry: Option<FontEntityMap>,
    /// A description of what the designer contributed to the font. For example, 'All the Latin and Arabic characters'.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contribution: Option<String>,
    /// "When the designer started to contribute to the font design.
    #[serde(rename = "startDate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// When the designer ended contributions to the font design.
    #[serde(rename = "endDate")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
}

/// The data structure used to store a reference to an external URL and its hash.
/// We use a socket/plug here to allow hashed-ext-uri-map to be used in individual files
/// without having the map defined in the same file
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct HashedExtUriMap {
    /// http/https URI reference
    pub url: ExtUrlType,
    /// A string identifying the cryptographic hash algorithm used to compute the hash on this URI's data, taken from the C2PA hash algorithm identifier list. Unlike alg fields in other types, this field is mandatory here.
    pub alg: String,
    ///  byte string containing the hash value
    pub hash: serde_bytes::ByteBuf,
    /// IANA media type of the data
    #[serde(rename = "dc:format")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dc_format: Option<FormatString>,
    /// Number of bytes of data
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<SizeType>,
    /// additional information about the data's type
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_types: Option<Vec<AssetTypeMap>>,
}

/// with CBOR Head (#) and tail ($) are introduced in regexp, so not needed explicitly
pub type ExtUrlType = String;

/// The data structure used to store a reference to a URL within the same JUMBF and its hash. We use a socket/plug here to allow hashed-uri-map to be used in individual files without having the map defined in the same file
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct HashedUriMap {
    /// JUMBF URI reference
    pub url: crate::jumbf_uri::JumbfUri,
    /// A string identifying the cryptographic hash algorithm used to compute all hashes in this claim, taken from the C2PA hash algorithm identifier list. If this field is absent, the hash algorithm is taken from an enclosing structure as defined by that structure. If both are present, the field in this structure is used. If no value is present in any of these places, this structure is invalid; there is no default.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alg: Option<String>,
    ///  byte string containing the hash value
    pub hash: serde_bytes::ByteBuf,
}

/// Assertion that describes an ingredient used in the asset
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct IngredientMap {
    /// name of the ingredient
    #[serde(rename = "dc:title")]
    pub dc_title: String,
    /// Media Type of the ingredient
    #[serde(rename = "dc:format")]
    pub dc_format: FormatString,
    /// value of the ingredient's `xmpMM:DocumentID`
    #[serde(rename = "documentID")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    /// unique identifier, such as the value of the ingredient's `xmpMM:InstanceID`
    #[serde(rename = "instanceID")]
    pub instance_id: String,
    /// The relationship of this ingredient to the asset it is an ingredient of.
    pub relationship: RelationChoice,
    /// hashed_uri reference to the C2PA Manifest of the ingredient
    #[serde(skip_serializing_if = "Option::is_none")]
    pub c2pa_manifest: Option<HashedUriMap>,
    /// hashed_uri reference to an ingredient thumbnail
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<HashedUriMap>,
    /// validation status of the ingredient
    #[serde(rename = "validationStatus")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub validation_status: Option<Vec<StatusMap>>,
    /// additional information about the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
}

/// Version 2 (v2) of the ingredient assertion
/// Assertion that describes an ingredient used in the asset
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct IngredientMapV2 {
    /// name of the ingredient
    #[serde(rename = "dc:title")]
    pub dc_title: String,
    /// Media Type of the ingredient
    #[serde(rename = "dc:format")]
    pub dc_format: FormatString,
    /// The relationship of this ingredient to the asset it is an ingredient of.
    pub relationship: RelationChoice,
    /// value of the ingredient's `xmpMM:DocumentID`
    #[serde(rename = "documentID")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    /// unique identifier, such as the value of the ingredient's `xmpMM:InstanceID`
    #[serde(rename = "instanceID")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance_id: Option<String>,
    /// hashed_uri reference to an embedded data assertion or a hashed_ext_uri to external data
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<ciborium::Value>,
    /// additional information about the data's type to the ingredient V2 structure.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_types: Option<Vec<AssetTypeMap>>,
    /// hashed_uri reference to the C2PA Manifest of the ingredient
    #[serde(skip_serializing_if = "Option::is_none")]
    pub c2pa_manifest: Option<HashedUriMap>,
    /// hashed_uri reference to a thumbnail in a embedded data assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<HashedUriMap>,
    /// validation status of the ingredient
    #[serde(rename = "validationStatus")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub validation_status: Option<Vec<StatusMap>>,
    /// Additional description of the ingredient
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// URI to an informational page about the ingredient or its data
    #[serde(rename = "informational_URI")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub informational_uri: Option<String>,
    /// additional information about the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
}

/// Version 3 (v3) of the ingredient assertion
/// Assertion that describes an ingredient used in the asset
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct IngredientMapV3 {
    /// name of the ingredient
    #[serde(rename = "dc:title")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dc_title: Option<String>,
    /// Media Type of the ingredient
    #[serde(rename = "dc:format")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dc_format: Option<FormatString>,
    /// The relationship of this ingredient to the asset it is an ingredient of.
    pub relationship: RelationChoice,
    /// Results from the claim generator performing full validation on the ingredient asset
    #[serde(rename = "validationResults")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub validation_results: Option<ValidationResultsMap>,
    /// unique identifier such as the value of the ingredient's `xmpMM:InstanceID`
    #[serde(rename = "instanceID")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance_id: Option<String>,
    /// hashed_uri reference to an embedded data assertion or a hashed_ext_uri to external data
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<ciborium::Value>,
    /// additional information about the data's type to the ingredient V3 structure
    #[serde(rename = "dataTypes")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_types: Option<Vec<AssetTypeMap>>,
    /// hashed_uri to the box corresponding to the active manifest of the ingredient
    #[serde(rename = "activeManifest")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_manifest: Option<HashedUriMap>,
    /// hashed_uri to the Claim Signature box in the C2PA Manifest of the ingredient
    #[serde(rename = "claimSignature")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub claim_signature: Option<HashedUriMap>,
    /// hashed_uri reference to a thumbnail in a embedded data assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<HashedUriMap>,
    /// Additional description of the ingredient
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// URI to an informational page about the ingredient or its data
    #[serde(rename = "informationalURI")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub informational_uri: Option<String>,
    /// Whether soft bindings were matched
    #[serde(rename = "softBindingsMatched")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub soft_bindings_matched: Option<bool>,
    /// Array of algorithm names used for discovering the active manifest
    #[serde(rename = "softBindingAlgorithmsMatched")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub soft_binding_algorithms_matched: Option<Vec<String>>,
    /// additional information about the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
}

pub type FormatString = String;

/// Choices that describe the reason for how the ingredient is related to the asset
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum RelationChoice {
    /// Choices that describe the reason for how the ingredient is related to the asset
    #[serde(rename = "parentOf")]
    ParentOf,
    #[serde(rename = "componentOf")]
    ComponentOf,
    #[serde(rename = "inputTo")]
    InputTo,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct LivevideoSegmentMap {
    /// monotonically increasing sequence number for each segment
    pub entries: std::collections::HashMap<String, u64>,
    /// A unique "streamId" identifying the live video stream
    pub entries_2: std::collections::HashMap<String, String>,
    /// method used to ensure continuity between segments
    pub entries_3: std::collections::HashMap<String, String>,
    /// additional fields as needed
    pub entries_4: std::collections::HashMap<String, ciborium::Value>,
}

/// when continuityMethod == c2pa.manifestId, additional fields include:
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct LivevideoSegmentMapManifestId {
    /// <<manifest-identifier>> of the previous segment's C2PA Manifest
    pub entries: std::collections::HashMap<String, String>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum MaxTstrLength {
    N1000000,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct MultiAssetHashMap {
    /// An array of one or more hashes for individual parts of the multi-part file
    pub parts: Vec<PartHashMap>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct ByteRangeLocator {
    /// The byte offset of the part within the file
    #[serde(rename = "byteOffset")]
    pub byte_offset: u64,
    /// The length of the part
    pub length: u64,
}

/// this is a special CDDL map of choices (meaning that only one of the following can be present)
/// The byte offset & length of the part within the file
/// An XPath to the BMFF box of the part
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct LocatorMap {
    #[serde(rename = "byte-range-locator")]
    pub byte_range_locator: ByteRangeLocator,
    #[serde(rename = "bmffBox")]
    pub bmff_box: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct PartHashMap {
    /// The location of the part within the file
    pub location: LocatorMap,
    /// hashed_uri to the hash assertion of the part
    #[serde(rename = "hashAssertion")]
    pub hash_assertion: HashedUriMap,
    /// If the part is optional and can be discarded
    #[serde(skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
}

/// CBOR version of rVals and related structures based on JSON schema in https://www.etsi.org/deliver/etsi_ts/119100_119199/11918201/01.01.01_60/ts_11918201v010101p.pdf section 5.3.5.2
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct RVals {
    #[serde(rename = "ocspVals")]
    pub ocsp_vals: Vec<serde_bytes::ByteBuf>,
}

/// Data structure to supply session keys used for live-video validation
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct SessionKeysData {
    /// one or more session keys
    pub entries: std::collections::HashMap<String, Vec<SessionKey>>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct SessionKey {
    /// session key used to sign the `verifiable-segment-info-map`, note: semantics need to require kid in COSE_Key
    pub entries: std::collections::HashMap<String, CoseKey>,
    /// minimum sequence number that can be signed with this key
    pub entries_2: std::collections::HashMap<String, u64>,
    /// CBOR tag 0 (RFC 3339 date-time)
    pub entries_3: std::collections::HashMap<String, String>,
    /// seconds from createdAt, key is valid for this period between createdAt and createdAt + validityPeriod
    pub entries_4: std::collections::HashMap<String, u64>,
    /// A signature of the Signer's end-entity certificate, using the session key `key`, enabling verification that the session key is associated with this Signer
    pub entries_5: std::collections::HashMap<String, CoseSign1>,
}

/// The data structure used to store one or more soft bindings across some or all of the asset's content
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct SoftBindingMap {
    /// A string identifying the soft binding algorithm and version of that algorithm used to compute the value, taken from the C2PA soft binding algorithm list. If this field is absent, the algorithm is taken from the `alg_soft` value of the enclosing structure. If both are present, the field in this structure is used.  If no value is present in any of these places, this structure is invalid; there is no default.
    pub alg: String,
    pub blocks: Vec<SoftBindingBlockMap>,
    /// zero-filled byte string used for filling up space
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pad: Option<serde_bytes::ByteBuf>,
    /// zero-filled byte string used for filling up space
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pad2: Option<serde_bytes::ByteBuf>,
    /// (optional) a human-readable description of what this hash covers
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// (optional) CBOR byte string describing parameters of the soft binding algorithm.
    #[serde(rename = "alg-params")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alg_params: Option<serde_bytes::ByteBuf>,
    /// (optional) Additional metadata of the soft binding. Useful for binding-specific information
    #[serde(rename = "bindingMetadata")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub binding_metadata: Option<SoftBindingMetadataMap>,
    /// Unused and deprecated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct SoftBindingBlockMap {
    pub scope: SoftBindingScopeMap,
    /// CBOR byte string describing, in algorithm specific format, the value of the soft binding computed over this block of digital content"
    pub value: serde_bytes::ByteBuf,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct SoftBindingScopeMap {
    /// deprecated, CBOR byte string describing, in algorithm specific format,  the part of the digital content over which the soft binding value has been computed"
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extent: Option<serde_bytes::ByteBuf>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timespan: Option<SoftBindingTimespanMap>,
    /// CBOR object defined in regions-of-interest.cddl
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<RegionMap>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct SoftBindingTimespanMap {
    /// Start of the time range (as milliseconds from media start) over which the soft binding value has been computed.
    pub start: u64,
    /// End of the time range (as milliseconds from media start) over which the soft binding value has been computed.
    pub end: u64,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct SoftBindingMetadataMap {
    /// Additional description of the implementation or author of the binding or the algorithm
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Contact information for the implementation or author of the binding or the algorithm,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact: Option<String>,
    /// A web page containing more details about the implementation or author of the binding or the algorithm.
    #[serde(rename = "informationalUrl")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub informational_url: Option<String>,
    pub entries: std::collections::HashMap<String, ciborium::Value>,
}

/// Possible values
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(untagged)]
pub enum TrainingMiningChoice {
    /// Possible values
    #[serde(rename = "allowed")]
    Allowed,
    #[serde(rename = "notAllowed")]
    NotAllowed,
    #[serde(rename = "constrained")]
    Constrained,
}

/// Description of the data structure
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct TrainingMiningMapEntry {
    #[serde(rename = "use")]
    pub use_: TrainingMiningChoice,
    /// information about the use of `constrained`
    #[serde(skip_serializing_if = "Option::is_none")]
    pub constraint_info: Option<String>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct TrainingMiningMap {
    #[serde(rename = "c2pa.data_mining")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub c2pa_data_mining: Option<TrainingMiningMapEntry>,
    #[serde(rename = "c2pa.ai_inference")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub c2pa_ai_inference: Option<TrainingMiningMapEntry>,
    #[serde(rename = "c2pa.ai_training")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub c2pa_ai_training: Option<TrainingMiningMapEntry>,
    #[serde(rename = "c2pa.ai_generative_training")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub c2pa_ai_generative_training: Option<TrainingMiningMapEntry>,
    /// allow for any other custom use case
    pub entries: std::collections::HashMap<String, ciborium::Value>,
    /// additional information about the assertion
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AssertionMetadataMap>,
}

/// CBOR version of tstContainer and related structures based on JSON schema at
/// https://forge.etsi.org/rep/esi/x19_182_JAdES/raw/v1.1.1/19182-jsonSchema.json
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct TstContainer {
    #[serde(rename = "tstTokens")]
    pub tst_tokens: Vec<TstToken>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct TstToken {
    pub val: serde_bytes::ByteBuf,
}

/// The data structure used to store a reference to an external URI WITHOUT a hash.
/// This might include, for example, http/https reference or URI reference to a smart
/// contract under CAIP-10 convention
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct UnhashedExtUriMap {
    /// URI reference
    pub url: String,
    /// IANA media type of the data
    #[serde(rename = "dc:format")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dc_format: Option<FormatString>,
    /// Number of bytes of data
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<SizeType>,
    /// additional information about the data's type
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_types: Option<Vec<AssetTypeMap>>,
}

pub type VerifiableSegmentInfo = CoseSign1Tagged;

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct SegmentInfoMap {
    /// monotonically increasing sequence number for each segment
    pub entries: std::collections::HashMap<String, u64>,
    /// C2PA c2pa.hash.bmff.v3
    pub entries_2: std::collections::HashMap<String, BmffHashMap>,
    /// shall be as described in <<manifest-identifier>>
    pub entries_3: std::collections::HashMap<String, String>,
    /// optional hashed-ext-uri-map to where manifest can be retrieved
    pub entries_4: std::collections::HashMap<String, HashedExtUriMap>,
}
