; Describes a reference to an alternative version of the content 
; (e.g. an original preservation image in Exif, a secure capture from TEE, etc.)
alternative-content-representation = 
  original-preservation-image-representation 
  / generic-representation

;The original-preservation-image-representation describes the location of the original captured scene image.
original-preservation-image-representation = {
  "type": "exif.originalPreservationImage",
  "parameters": original-preservation-image-params
}

original-preservation-image-params = {
  ? "multiAssetPartIndex": uint ; The zero-based index of the element within the parts array of the corresponding c2pa.hash.multi-asset assertion that uniquely identifies the location of the OPI.
  ? "embeddedOriginalPreservationImage": hashed-uri-map, ; hashed URI reference to the embedded data assertion containing OPI, or to another assertion that is technically equivalent to an embedded data assertion (e.g., c2pa.thumbnail.claim).
}

generic-representation = {
  "type": tstr .regexp "([\\da-zA-Z_-]+\\.)+[\\da-zA-Z_-]+",
  "parameters": { * tstr => any }
}