; assertion used to carry live video segment information
; this assertion shares `sequenceNumber` semantics with `verifiable-segment-info-map`

livevideo-segment-map = {
    "sequenceNumber" => uint,  					; monotonically increasing sequence number for each segment
    "streamId" => tstr,        					; A unique "streamId" identifying the live video stream
    "continuityMethod" => tstr,         		; method used to ensure continuity between segments 
    * tstr => any                              ; additional fields as needed
}

; when continuityMethod == c2pa.manifestId, additional fields include:
livevideo-segment-map-manifestId = {
    "previousManifestId" => tstr,             ; <<manifest-identifier>> of the previous segment's C2PA Manifest
}
