;Align regions-of-interest object structure in soft-binding assertions with that used for other purposes
;# include regions-of-interest 

;The data structure used to store one or more soft bindings across some or all of the asset's content
soft-binding-map = {
  "alg": tstr, ; A string identifying the soft binding algorithm and version of that algorithm used to compute the value, taken from the C2PA soft binding algorithm list. If this field is absent, the algorithm is taken from the `alg_soft` value of the enclosing structure. If both are present, the field in this structure is used.  If no value is present in any of these places, this structure is invalid; there is no default.
  "blocks": [1* soft-binding-block-map],
  ? "pad": bytes, ; zero-filled byte string used for filling up space
  ? "pad2": bytes, ; zero-filled byte string used for filling up space
  ? "name": tstr .size (1..max-tstr-length), ; (optional) a human-readable description of what this hash covers
  ? "alg-params": bstr, ; (optional) CBOR byte string describing parameters of the soft binding algorithm. 
  ? "bindingMetadata": soft-binding-metadata-map, ; (optional) Additional metadata of the soft binding. Useful for binding-specific information
  ? "url": uri, ; Unused and deprecated. 
  ? "metadata": $assertion-metadata-map, ; additional information about the assertion
}

soft-binding-block-map = {
  "scope": soft-binding-scope-map,
  "value": bstr, ; CBOR byte string describing, in algorithm specific format, the value of the soft binding computed over this block of digital content"
}

soft-binding-scope-map = {
  ? "extent": bstr, ;deprecated, CBOR byte string describing, in algorithm specific format,  the part of the digital content over which the soft binding value has been computed"
  ? "timespan":soft-binding-timespan-map,
  ? "region": region-map, ; CBOR object defined in regions-of-interest.cddl
}

soft-binding-timespan-map = {
  "start": uint, ; Start of the time range (as milliseconds from media start) over which the soft binding value has been computed.
  "end": uint,   ; End of the time range (as milliseconds from media start) over which the soft binding value has been computed.
}

soft-binding-metadata-map = {
  ? "description": tstr .size (1..max-tstr-length) ; Additional description of the implementation or author of the binding or the algorithm
  ? "contact": tstr .size (1..max-tstr-length) ; Contact information for the implementation or author of the binding or the algorithm,
  ? "informationalUrl": tstr .size (1..max-tstr-length) ; A web page containing more details about the implementation or author of the binding or the algorithm.
* tstr => any
}
